### ISSUE TITLE
Missing WinStoreAppLinks folder

### ISSUE THREAD

**Issue by filcole** [rickstaa/Todoist_Global_Shortcuts_WIN10#1]
On point 6 of the instructions there is no "WinStoreAppLinks" folder within the zip file here: https://github.com/rickstaa/Todoist_Global_Shortcuts_WIN10/archive/master.zip

**Comment by rickstaa** [comment]
Dear Filcole,

I'm sorry for the inconvenience I fixed the issue. If you download the zip again, it now includes the folder. Can you maybe check if the install process is working? 

Can you maybe keep me posted on if it is working? I'm unsure if the shortcut to Todoist in the WinStoreAppLinks will work on other peoples PCS. Otherwise, I have to create a small installer or update the README file.

In the meantime the shortcut didn't work here is what you should do to get the script working.

1. As it is tough to open WinStoreApps by coding you need to create a "WinStoreAppLinks" folder in your "Program Files" folder.
2. Open this folder in Finder.
3. Press the start key.
4. Drag the Todoist Icon to the "WinStoreAppLinks" folder this will create the shortcut I use to launch the program.

Greetings,
Thanks in advance,
Rick Staa,

**Comment by rickstaa** [comment]
I created an installer hope that helps ;).

**Comment by rickstaa** [comment]
Dear Filcole,

I'm sorry for the inconvenience I fixed the issue. I just uploaded the new version. In this version, there is an installer. In the readme, you can find how to install the script.

Greetings,
Thanks in advance,
Rick Staa,
